# Generated by Django 5.2.13 on 2026-05-27 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code',
            field=models.CharField(default='CDQQAQKN', max_length=30),
        ),
    ]
